name: 'Publish to Visual Studio Marketplace'


on:
  create:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -o $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
